services:

  rewards-service:
    image: openjdk:22-jdk-oracle
    container_name: rewardsimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    depends_on:
      - rewards-db
    env_file:
      - .env
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/RewardsService-v1.0.7.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  rewards-db:
    image: mongo:latest
    container_name: rewardsdb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_rewards:/etc/mongo
      - mongo_rewards_data:/data/db
      - mongo_rewards_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:
    name: greenspot_net

volumes:
  mongo_rewards:
  mongo_rewards_data:
  mongo_rewards_config: